### ISSUE TITLE
Ability to run Golang CI Service

### ISSUE THREAD

**Issue by sladyn98** [golangci/golangci-lint#1020]
Golang CI has been an amazing project and it has helped thousands of people thank you so much for this amazing product. I did go through your blog that the service was being terminated on the 15th of April and that is indeed very sad.  I have been thinking of running these servers on my own with the help of my team and thereby keeping this community alive.
I would love to know the cost and procedure of hosting these services and how would we go about it.If you would be up for a follow up call or if you can write down the overhead  of machines required and the cost of running it on a monthly basis, I can really help in keeping it alive.
Thanks and Cheers
CC: 
@jirfag @ernado

**Comment by ernado** [comment]
Seems like it is real having enough human resources. Currently I'm trying to allocate resources to maintain *golangci-lint*, but SaaS parts like https://github.com/golangci/golangci-api https://github.com/golangci/golangci-web https://github.com/golangci/golangci-worker require maintenance too (e.g. updates, feature development, issue triage and PR review). 

I will investigate what we can do and leave a reply here.

I've had an idea to split free and paid plans, so we can use plans for OSS projects, and there are other ways to optimize.

**Comment by jirfag** [comment]
hi,
thank you,
we're suggesting using our [github action](https://github.com/golangci/golangci-lint-action) as the replacement for golangci.com.

We've invested a lot of effort into so, so now It can do everything that golangci.com could do except it makes GitHub annotations [instead of comments](https://github.com/golangci/golangci-lint-action/issues/5).
