### ISSUE TITLE
Change in release-asset names breaks automation

### ISSUE THREAD

**Issue by Helcaraxan** [golangci/golangci-lint#1157]
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Between 1.26.0 and 1.27.0 the name of the Windows release assets has changed from:
```
golangci-lint-1.26.0-windows-amd64.zip
```
to
```
golangci-lint.exe-1.27.0-windows-amd64.zip
```

This change in format is a pain to manage in automated install scripts as it deviates from what existed before and from the format used for Linux and OSX assets.

It appears that the asset names are generated via `goreleaser` so this might be due to some change in that tool?

It would be very much appreciated if this change was reverted.

**Comment by joemiller** [comment]
https://github.com/goreleaser/goreleaser/issues/1500

**Comment by joemiller** [comment]
Current workaround: pin the installer to 1.26.0

```
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b "$HOME/bin" v1.2.6.0
```

**Comment by joemiller** [comment]
A fix is in the works: https://github.com/goreleaser/goreleaser/pull/1539

**Comment by joemiller** [comment]
This should be fixed in the next goreleaser (0.136.0) - https://github.com/goreleaser/goreleaser/pull/1539 - which is not available yet but should be soon.

**Comment by Helcaraxan** [comment]
Thank you very much for the quick reaction @joemiller !

**Comment by joemiller** [comment]
@Helcaraxan n/p, although I am just relaying communications =)

I expect the fix will be in goreleaser 0.136.0 but there's an issue blocking goreleaser's release pipeline at the moment - https://github.com/goreleaser/goreleaser/issues/1544

golangci-lint could probably do any of the following to resolve the issue on this side:

1. wait for goreleaser 0.136.0, generate a new release
2. Modify the golangci-lint v1.27.0 release assets manually to remove the `.exe` from the 2 windows zips. Also need to update the checksums file
3. Pin goreleaser to v0.133.0 and cut a new release (or older, I haven't checked the exact version the bug was introduced) by adding `version:` attribute to the github action here: https://github.com/golangci/golangci-lint/blob/master/.github/workflows/tag.yml#L23-L25 eg:
```yaml
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.133.0
```

**Comment by ernado** [comment]
I've copied `golangci-lint.exe-1.27.0-windows-386.zip` to `golangci-lint-1.27.0-windows-386.zip` (same for amd64) and added lines to checksum file manually. 
Files should be identical.

Please check.

**Comment by joemiller** [comment]
@ernado -
Result from a github action run:

```console
golangci/golangci-lint info checking GitHub for latest tag
golangci/golangci-lint info found version: 1.27.0 for v1.27.0/windows/amd64
Archive:  golangci-lint-1.27.0-windows-amd64.zip
  inflating: golangci-lint.exe-1.27.0-windows-amd64/LICENSE  
  inflating: golangci-lint.exe-1.27.0-windows-amd64/README.md  
  inflating: golangci-lint.exe-1.27.0-windows-amd64/golangci-lint.exe  
install: cannot stat '/tmp/tmp.3s9Hj8dnn2/golangci-lint-1.27.0-windows-amd64/golangci-lint.exe': No such file or directory
##[error]Process completed with exit code 1.
```

Looks like the directory inside the zip contains ".exe" and that must matter to the install script.

**Comment by ernado** [comment]
Meh.
Let's fix it with next release.

**Comment by joemiller** [comment]
goreleaser 0.136.0 is available now and includes the fix https://github.com/goreleaser/goreleaser/releases

**Comment by SVilgelm** [comment]
Closing due to fixed. I checked the [latest release](https://github.com/golangci/golangci-lint/releases/tag/v1.28.3) and the windows asset name does not contain `exe`
