### ISSUE TITLE
Addition of nancy for checking vulnerable dependencies

### ISSUE THREAD

**Issue by kishaningithub** [golangci/golangci-lint#1200]
I would like to have [nancy](https://github.com/sonatype-nexus-community/nancy) integrated as part of golangci-lint. [Nancy](https://github.com/sonatype-nexus-community/nancy) is a a tool to check for vulnerabilities in Golang dependencies, powered by Sonatype OSS Index

**Comment by sayboras** [comment]
This tool didn't seems to implement go analysis, so it will be hard to integrate to golangci-lint. 

Moreover, I just have quick look on nancy repo, I don't think it's designed to use as library either.

**Comment by SVilgelm** [comment]
I think it's not a good idea, because Nancy does a lot of http requests, and it will be very very slow process. Of course the cache will reduce the wait time, but anyway it requires an internet connectivity, when all other linters work locally.

I think it's a good idea to integrate the `nancy` tool into PR workflow for golangci-lint development process, but not as a linter

**Comment by SVilgelm** [comment]
Closing issue, since all are agreed that Nancy should not be integrated as a linter, but should be used as an independent tool
