### ISSUE TITLE
Real time communication

### ISSUE THREAD

**Issue by iwankgb** [golangci/golangci-lint#1233]
@golangci/team, I think it would be useful to have a real time communication channel so that we are able to use slightly faster communication than issues and PRs. It could help to coordinate work around releases etc.
Do you have any opinion on this? Would Freenode IRC channel be enough or you prefer Slack or something else?

**Comment by SVilgelm** [comment]
Hi @iwankgb,
Here is my thoughts: The real time communication is useful only for the people who work in same/very close timezone.
Slack has some limitations for the free accounts, IRC is rarely used now. If you really want a real time communication, then I would recommend Gitter, it has a good integration with the Github.
But since the golangci/team contains people all over the world I would recommend to use the team's discussions: https://github.com/orgs/golangci/teams/team

I created first discussion for the team: https://github.com/orgs/golangci/teams/team/discussions/1

**Comment by Helcaraxan** [comment]
Just a thought: for Slack you can start with a dedicated channel on the Go slack. There are plenty of OSS Go projects that have one there.

This would also allow users to dip in more easily for questions and / or issue reporting. In the past I've had multiple occasions where I would have loved to be able to reach out to contributors of the project but there was no channel.

**Comment by SVilgelm** [comment]
Oh yes, thank you @Helcaraxan, I totally forgot about the gophers slack. The `golangci-lint` channel already exists. Anyone can join using this link: https://invite.slack.golangbridge.org/

**Comment by SVilgelm** [comment]
and then using this link to join the channel: https://gophers.slack.com/app_redirect?channel=golangci-lint
