### ISSUE TITLE
Support overriding in WSL

### ISSUE THREAD

**Issue by alenkacz** [golangci/golangci-lint#1737]
**Is your feature request related to a problem? Please describe.**
Make it possible to pass this through wsl config https://github.com/bombsimon/wsl/blob/a6e08b33286b24ec81b47c17b60608e8b02a69f5/wsl.go#L92
https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/wsl.go

**Describe the solution you'd like**
Add new config setting for golangcilint and pass it through to wsl

**Comment by alenkacz** [comment]
I can contribute this if I get a 👍 that this feature would be accepted

**Comment by bombsimon** [comment]
Hi! I'm the author of `wsl` and I just created [a new release](https://github.com/bombsimon/wsl/releases/tag/v3.2.0) so you you can bump the version in `golangci-lint`. I had plans last year to do a re-write but didn't finish it so this is about time. It's currently [four fixed issues](https://github.com/bombsimon/wsl/issues?q=is%3Aissue+is%3Aopen+label%3Agolangci-only) not merged upstream to `golangci-lint` so that would be nice!

Please feel free to bump `wsl` to `v3.2.0` and add the missing configuration settings so they match 1:1 and we'll approve/merge.
