### ISSUE TITLE
Support gosec (gas) linter options

### ISSUE THREAD

**Issue by wfernandes** [golangci/golangci-lint#177]
It would be nice to support `gas` linter options like `-include` and `-exclude` as part of the `linters-settings` in the golangci-lint config files.
Thanks.

**Comment by wfernandes** [comment]
@jirfag Just checking in. I haven't checked myself recently, but are gosec (gas) linter options supported?

**Comment by ats0stv** [comment]
Yes to try it with the latest golangci-lint. From the docs, https://golangci-lint.run/usage/linters/ it says its possible to enable gosec. Will post back after trying

**Comment by wfernandes** [comment]
Yeah I think enabling `gosec` will work. Just curious about the `linters-settings` in the configuration - https://golangci-lint.run/usage/configuration/.

Thanks for checking @ats0stv

**Comment by ats0stv** [comment]
Thanks @wfernandes.

I checked, with -E option and also in another attempt to disable all other linters and enable just gosec. However, in both cases, it does not seem to work. I believe this bug is still valid.

**Comment by Nivl** [comment]
It would be nice to be able to fully configure it. Right now golangci-lint is using the [default configuration](https://github.com/golangci/golangci-lint/blob/38d298c2c859eda2a2d09a13fda6ee8a1fe065cf/pkg/golinters/gosec.go#L27). Being able to set options on every single rule they have ([like using 644 instead of 600 for G306](https://github.com/securego/gosec/issues/107#issuecomment-271748691)) would be much more useful. Right now I have to silent most rules because they are too strict, even though they can be configured.

**Comment by aknuds1** [comment]
I have the same problem, that I would like to configure gosec's rules via golangci-lint.
