### ISSUE TITLE
GoKart support

### ISSUE THREAD

**Issue by mykter** [golangci/golangci-lint#2189]
### Your feature request related to a problem? Please describe.

 [GoKart](https://github.com/praetorian-inc/gokart) is a new stand-alone security-focused static analysis tool.

### Describe the solution you'd like.

Add support for GoKart. It uses `go/analysis`.

### Describe alternatives you've considered.

Run GoKart separately to golangci-lint.

**Comment by SVilgelm** [comment]
I think it will be much faster if you can raise a PR. Any new linters that are not already covered by extent are welcome

**Comment by shubham1172** [comment]
I would like to work on this, can you please assign this to me?

**Comment by SVilgelm** [comment]
no worries, you can just raise a PR

**Comment by anoymouscoder** [comment]
Hi, @shubham1172 I am wondering if you are still working on this? If not, I'd like to complete this issue XD

**Comment by shubham1172** [comment]
Hello @anoymouscoder, you can take it up!

**Comment by anoymouscoder** [comment]
@SVilgelm Because this issue has been raised for a long time, I would like to reconfirm whether there are existent or similar linters

**Comment by anoymouscoder** [comment]
> @SVilgelm Because this issue has been raised for a long time, I would like to reconfirm whether there are existent or similar linters


@ldez Could you help confirm this?

**Comment by bombsimon** [comment]
By looking at [the list of linters](https://golangci-lint.run/usage/linters/) a linter that seems related is [gosec](https://github.com/securego/gosec) but no full overlap. 

I noticed that GoKart seems somewhat abandoned. Last commit was 26 January 2022 (7+ months ago) and there are issues and PRs back from September 2021 that has got no attention from any maintainer. This is not a great sign since we would need to be able to get feedback from potential issues or PRs that we might discover if implementing this in `golangci-lint`.

**Comment by anoymouscoder** [comment]
@bombsimon  Thanks for your reply, I got it. So do we need to close this issue or keep watching the gokart project?

**Comment by bombsimon** [comment]
GoKart is deprecated since April 2024 without any activity the last 2 years. There was an [issue filed](https://github.com/praetorian-inc/gokart/issues/95) just before it got archived that never got answer. Also can't find anything in their blog or similar but I think this is enough to not accept any integration with `golangci-lint`.
