### ISSUE TITLE
The link of GitHub Releases Stats badge in docs is outdated

### ISSUE THREAD

**Issue by andig** [golangci/golangci-lint#2663]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

The downloads link on https://golangci-lint.run leads to https://somsubhra.com/github-release-stats?username=golangci&repository=golangci-lint which seems very odd.

### Version of golangci-lint

n/a

### Configuration file

n/a

### Go environment

n/a

### Verbose output of running

n/a

### Code example or link to a public repository

n/a

**Comment by SVilgelm** [comment]
it is not hijacked, the usage of somsubhra was introduced 2 years ago, then seems the site started using a somsibhra.github.io instead of .com. The url in README.md has been updated, but docs still has the old.
It should be synchronized with README and use this: `https://somsubhra.github.io/github-release-stats/?username=golangci&repository=golangci-lint`
