### ISSUE TITLE
Add it to chocolatey

### ISSUE THREAD

**Issue by frederikhors** [golangci/golangci-lint#2861]
### Your feature request related to a problem? Please describe.

Can you please add it to https://chocolatey.org?

### Describe the solution you'd like.

`choco` auto upgrade binaries in my Windows.

### Describe alternatives you've considered.

Manually install it on each release.

### Additional context.

Thank you.

**Comment by bombsimon** [comment]
Just browsing old issues and this seems to be fixed now (oh well, over a year ago) with https://github.com/goreleaser/goreleaser/pull/3509. Docs at https://goreleaser.com/customization/chocolatey/

**Comment by ldez** [comment]
It feels like a paid service :thinking:

**Comment by bombsimon** [comment]
> It feels like a paid service 🤔

I didn't dig too deep but at least it's not listed under [GoReleaser Pro](https://goreleaser.com/pro/) and the features that are have a little banner at the top in the docs so I think it should be fine.

**Comment by ldez** [comment]
There is an existing package https://community.chocolatey.org/packages/golangci-lint

**Comment by bombsimon** [comment]
Ping @glennsarti 

Maybe you can explain how you publish this for free and also consider transfering ownership or change/add maintainer if needed?

**Comment by glennsarti** [comment]
Hi all!

> Maybe you can explain how you publish this for free

So Chocolatey (the company) provides a Community Chocolatey Repository (https://docs.chocolatey.org/en-us/community-repository/). FWIW, it's built on the Nuget system which powers things like Visual Studio and other community package registries.

This is a free service, but of course has some limits (API limits, manual review process etc.) which is explained [here](https://docs.chocolatey.org/en-us/community-repository/community-packages-disclaimer)

> and also consider transferring ownership or change/add maintainer if needed?

Unfortunately, you can't transfer ownership, but I'd be more than happy to deprecate (which hides) all the versions I have published and add a note in my README to use your new package with a link to it.

> I see some code around it at https://github.com/glennsarti/ChocolateyPackages but I don't have any experience publishing to Chocolatey.

I use another tool (called Automatic Updates [1]) to automatically detect new package versions, and created new packages based on a template.

Short version:
* You need a `.nuspec` file [Here's the one for the latest version](https://github.com/glennsarti/ChocolateyPackages/blob/main/automatic/golangci-lint/golangci-lint.nuspec). This is the metadata about the package

* You need the actual install script. [Here's the one for the latest version](https://github.com/glennsarti/ChocolateyPackages/blob/main/automatic/golangci-lint/tools/chocolateyInstall.ps1). Because I'm using standard Chocolatey functions, it automatically knows how to uninstall. Which is why there is no uninstall script.

* You package them up using nuget
* You push the package to the repository using an API key

> And I need to understand how to not pay for chocolatey 😄

I think you may be confusing Chocolatey "The CLI Tool" and Chocolatey "The Licensed Extensions". The core tool is your usual free-for-use. But if you want management and support and such, that's when you pay. No different to many other product offerings

[1] AU is a hideous mess but it works.

**Comment by ldez** [comment]
Based on the settings message, I think you can add maintainers to your package:

> This setting allows users of the site to contact you about packages that you own using the 
Contact Maintainers form, or to request that you become a maintainer of their package. 

I created an account: https://community.chocolatey.org/profiles/golangci

**Comment by glennsarti** [comment]
> Based on the settings message, I think you can add maintainers to your package:

Huh well... it seems you can transfer packages - https://docs.chocolatey.org/en-us/community-repository/maintainers/package-maintainer-handover

I've asked my contacts at Chocolatey to see if this is the exact process to transfer ownership.  In which case, this should be fairly painless!

**Comment by glennsarti** [comment]
I can indeed transfer ownership. Excellent!

So for the record, @ldez Would you like me to add 'golangci' as a maintainer on that package.

Once you accept, I'm happy for you to remove me as a maintainer, which means it's all yours!

**Comment by ldez** [comment]
> Would you like me to add 'golangci' as a maintainer on that package.

Yes, please.

> Once you accept, I'm happy for you to remove me as a maintainer, which means it's all yours!

You can stay a maintainer of the package if you want.

**Comment by glennsarti** [comment]
Request sent.

**Comment by glennsarti** [comment]
I'll disable my automated release of golangci-lint in the mean time. I can always re-enable or even manually release packages if needs be,

**Comment by glennsarti** [comment]
Confirming that I've disable my package updater so we won't be competing.  And I can see the new versions available on Chocolatey.

On a personal note, thanks for being so respectful and kind for this transition. It means a lot ❤️
