### ISSUE TITLE
Add golang.org/x/vuln/vulncheck as a linter

### ISSUE THREAD

**Issue by joerdav** [golangci/golangci-lint#3094]
### Your feature request related to a problem? Please describe.

govulncheck allows you to check if your code is calling any vulnerable code.

### Describe the solution you'd like.

Add https://pkg.go.dev/golang.org/x/vuln/vulncheck as a linter.

### Describe alternatives you've considered.

I can't find another vulnerability checker that can determine if the vulnerable code is being called or not.

**Comment by ldez** [comment]
Hello,

There are several problems:
- vulncheck doesn't use the `go/analysis` API
- vulncheck is not designed to be used as a library

https://golangci-lint.run/contributing/new-linters/#how-to-add-a-public-linter-to-golangci-lint
https://github.com/golang/vuln/tree/master/cmd/govulncheck

So I will decline this proposal.

**Comment by luxifer** [comment]
Hi,

I think the issue should be re-opened because of https://go.dev/blog/vuln and the [vulncheck](https://go.dev/blog/golang.org/x/vuln/vulncheck) library that's used by the command `govulncheck`. I can work on it

**Comment by ryancurrah** [comment]
Looks like they have a API now, I havent looked at it though.

> To directly integrate vulnerability checking into other tools and processes, the [vulncheck](https://pkg.go.dev/golang.org/x/vuln/vulncheck) package exports govulncheck’s functionality as a Go API.

**Comment by Dentrax** [comment]
It seems mentioned PR is currently _Draft_, and since they have an API as Ryan mentioned above, we can re-open this one. @ldez Wdyt?

**Comment by ldez** [comment]
As vulncheck is based on SSA, I think the integration will not work but I will re-open.

**Comment by Dentrax** [comment]
Thanks!

@luxifer Is your PR final? If so, can you please remove draft?

**Comment by Dentrax** [comment]
I can help you on that if you add me as collaborator in your fork.

**Comment by acabarbaye** [comment]
Having this tool running as part of the linters will be extremely useful

**Comment by ldez** [comment]
I didn't really provide my opinion on this topic: I think that vulncheck is not a linter.
It's a vulnerability/security tool and it should be run as a standalone tool.

Also, as the "rules" of vulncheck are outside of the configuration file, golangci-lint will ignore any changes because it's not a part of the cache.
This will lead to the same kind of problems as ruleguard (a part of go-critic) #1999

As you can understand, for now, I disagree with the integration of vulncheck, but I'm not alone on this project, and I can change my mind over time, I will wait for feedback from other maintainers.

I'm not making any decision at this time.

**Comment by luxifer** [comment]
I understand your concerns about that. And the afct that the database is external make it difficult to integrate properly with caching. Anyway, if it's not integrated, it's not a big deal for me and it helped me better understand the internal structure of this project.

**Comment by luxifer** [comment]
Maybe we can close this issue as well?

**Comment by ldez** [comment]
yes I will close it, thank you @luxifer
