### ISSUE TITLE
v1.48: `nolint` default config conlicts with `go fmt`  

### ISSUE THREAD

**Issue by amass01** [golangci/golangci-lint#3098]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

Latest (v1.48) nolintlint default config has a conflict with 1.19 gofmt. 
After #3002 `nolintlint` complains about leading spaces in `//nolint` comments
by default and the `gofmt` command re-adds the leading space.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
v1.48
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

```

</details>

### Go environment

<details>

```console
$ go version && go env
1.19
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
Error: directive `// nolint` should be written without leading space as `//nolint` (nolintlint)
```

</details>

### Code example or link to a public repository

<details>

```go
// nolint 
```

</details>

**Comment by ldez** [comment]
Hello,

Due to a change of `go fmt` inside go1.19.
We have to enforce the directive style.

So the option `allow-leading-space` has been dropped.

The syntax of directives is: `[a-zA-Z]+:[a-zA-Z].*`.
The spaces around `:` and after the `//` must be removed.

If you do that your IDE (ex: goland) will format the directive as a directive and it will not add extra space.

Related to:
https://github.com/golangci/golangci-lint/pull/3002
https://github.com/golangci/golangci-lint/issues/1658#issuecomment-1183148066

**Comment by amass01** [comment]
Noted, thank you
