### ISSUE TITLE
Add "gochecker" linter (or add support for its analyzers)

### ISSUE THREAD

**Issue by leonklingele** [golangci/golangci-lint#3724]
### Your feature request related to a problem? Please describe.

https://github.com/sv-tools/gochecker also is a multi-linter. It supports quite a lot of analyzers from the `golang.org/x/tools/go/analysis/passes` package.

Either these analyzers should be added to this project as well, or `gochecker` should be integrated in full.

### Describe the solution you'd like.

—

### Describe alternatives you've considered.

—

**Comment by ldez** [comment]
This "linter" is offtopic.

**Comment by SVilgelm** [comment]
omg, that "linter" is far away of readiness and should not be integrated to golangci-lint, because that is a aggregator for same linters as the golangci-lint

I just played around the multicheker (same as vet) and decided to make my work public.
The `gochecker` is good enough for small projects, but too slow for big ones
