### ISSUE TITLE
Add `go-geiger` linter

### ISSUE THREAD

**Issue by cristaloleg** [golangci/golangci-lint#4062]
### Your feature request related to a problem? Please describe.

Static code analysis tool to find unsafe usages in Go packages and their dependencies. https://github.com/jlauinger/go-geiger

https://dev.to/jlauinger/exploitation-exercise-with-unsafe-pointer-in-go-information-leak-part-1-1kga

### Describe the solution you'd like.

This linter is based on go/analysis so adding it should be a big deal.

### Describe alternatives you've considered.

Not adding

### Additional context.

Probably I can take it if this feature will be accepted.

**Comment by ldez** [comment]
> go-geiger helps developers to quickly identify which packages in the import tree of a Go package use unsafe.Pointer

This analyzer is not really a linter from the point of view of golangci-lint because it just finds and counts elements, i.e. it's a detector of unsafe inside dependencies, it's a decision helper.

The reports cannot be used to fix something because the reports are about dependencies (so outside the user code).

The way that golangci-lint works doesn't really allow report pointing outside of the user code base.
