### ISSUE TITLE
Add linter for `go mod verify`

### ISSUE THREAD

**Issue by seregayoga** [golangci/golangci-lint#4123]
### Your feature request related to a problem? Please describe.

You can verify your project's modules by `go mod verify`. It would be good to have such linter in golangci-lint.

### Describe the solution you'd like.

Add (and implement) a linter that will run `go mod verify`. It can have a name like `gomodverify`

### Describe alternatives you've considered.

You could run this command separetly but having it inside golangci-lint would be more convinient.

**Comment by bombsimon** [comment]
`golangci-lint` is mainly a tool to do static analysis on Go code and not to group tooling around Go. I'm not sure managing go modules falls in  the scope of a meta linter since running `go mod verify` isn't really linting. It feels similar to the discussion around `vulncheck` in #3094 which recently got closed. I'm also not sure how this would be implemented since there's currently no similar support.

**Comment by ldez** [comment]
For me it's the same thing as vulncheck, or `go mod tidy`: the tools are better by themselves and outside of the scope of golangci-lint.

**Comment by narqo** [comment]
@ldez @bombsimon could you help us understand the conceptual difference between `go vet` and `go mod verify` (_or `go mod tidy -check` if one got finally landed into go toolchain https://github.com/golang/go/issues/27005_). It would be helpful to expand on why `go vet` (or linters like `gomoddirectives`) are in the scope, but the proposed one isn't?

**Comment by ldez** [comment]
`go vet` is a tool to run analyzers that perform static code analysis.
We don't use `go vet` but we use `golang.org/x/tools/go/analysis` to run golangci-lint and provide an alternative to `go vet`.

`go mod` is a Go command to handle dependencies.

You can say that `gomoddirectives` or `depguard` are outside of the scope but their goals are not to handle dependencies but to analyze files syntactically.
