### ISSUE TITLE
Consider configuration-controllable version

### ISSUE THREAD

**Issue by tmc** [golangci/golangci-lint#4169]
### Your feature request related to a problem? Please describe.

It'd be great if the .golangci.yaml (et. al) files could specify the golangci-lint version number and have it resolve missing versions for users. This would make it easier for users to have identical local and CI results with low overhead.

### Describe the solution you'd like.

some means of specifying the golangci-lint version in configuration.

### Describe alternatives you've considered.

-

**Comment by bombsimon** [comment]
I think this is a duplicate of #3912, right?

It's been discussed before and my memory says that it's been out of scope for `golangci-lint` so far. So shameless self promotion but that's why I made [`gclv`](https://github.com/bombsimon/gclv) as a proof of concept to see how this could work. It allows you to specify the version of `golangci-lint` in `.golangci.yml` and use `gclv --run` as an alias for `golangci-lint --run` but ensuring the specified version is used.

Feel free to close this if you agree it's a duplicate.
