### ISSUE TITLE
gosec update?

### ISSUE THREAD

**Issue by JAORMX** [golangci/golangci-lint#597]
The gosec module that's used by golangci is a fork from the original one. It seems that it's a version from last year.

Would it be possible to use the original one? or to rebase and get a newer version of the gosec linter?

**Comment by dnwe** [comment]
More specifically, it would be great if we could pull in the 2.0.0 release of gosec — specifically to get the fix in PR https://github.com/securego/gosec/pull/311 which at the moment is causing false positives such as https://github.com/securego/gosec/issues/291 to be returned when gosec is enabled and run via golangci-lint rather than standalone

**Comment by dnwe** [comment]
@jirfag would you have a moment to reset golangci/gosec@master to the branch in https://github.com/golangci/gosec/pull/1? Then I can submit a PR to change the call in golangci-lint

**Comment by jirfag** [comment]
Hi, sorry for the slow response, I've updated gosec in https://github.com/golangci/golangci-lint/pull/681, please check
