### ISSUE TITLE
Different output between enabling all linters and only enabling one linter

### ISSUE THREAD

**Issue by iccengan** [golangci/golangci-lint#617]
1. Version:
```
golangci-lint --version
golangci-lint has version 1.17.1 built from 4ba2155 on 2019-06-10T09:06:49Z
```
2. no config file
3. 
```
go version go1.12.6 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/iccen/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/iccen/go_proj/test_proj"
GOPROXY=""
GORACE=""
GOROOT="/home/iccen/go"
GOTMPDIR=""
GOTOOLDIR="/home/iccen/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build132636320=/tmp/go-build -gno-record-gcc-switches"
```
4. 
When I ran: 
`golangci-lint run --enable-all --disable=govet --out-format=tab --deadline=60m --max-issues-per-linter=0 --max-same-issues=0 -j=2 | grep ineffassign` 
Output:
```
src/configcenter/src/apiserver/core/compatiblev2/service/host.go:409:4                                        ineffassign       ineffectual assignment to `hostTransType`
src/configcenter/src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go:42:9         ineffassign       ineffectual assignment to `asst`
```

However, if I ran: 
`golangci-lint run --disable-all --enable=ineffassign --out-format=tab --deadline=60m --max-issues-per-linter=0 --max-same-issues=0 -j=2 | grep ineffassign`
Output:
```
src/configcenter/src/apiserver/core/compatiblev2/service/host.go:409:4                                 ineffassign  ineffectual assignment to `hostTransType`
src/configcenter/src/apiserver/core/compatiblev2/service/set.go:341:3                                  ineffassign  ineffectual assignment to `msg`
src/configcenter/src/apiserver/core/compatiblev2/service/set.go:631:12                                 ineffassign  ineffectual assignment to `err`
src/configcenter/src/auth/extensions/host.go:103:4                                                     ineffassign  ineffectual assignment to `err`
src/configcenter/src/auth/extensions/host.go:110:4                                                     ineffassign  ineffectual assignment to `err`
src/configcenter/src/auth/extensions/host.go:117:4                                                     ineffassign  ineffectual assignment to `err`
src/configcenter/src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go:42:9  ineffassign  ineffectual assignment to `asst`
src/configcenter/src/scene_server/topo_server/service/object_group.go:131:2                            ineffassign  ineffectual assignment to `datas`
src/configcenter/src/source_controller/coreservice/core/host/modulehost/transfer.go:118:3              ineffassign  ineffectual assignment to `hostInfo`
src/configcenter/src/source_controller/coreservice/core/model/classification.go:261:2                  ineffassign  ineffectual assignment to `cnt`
src/configcenter/src/common/util/valid.go:63:4                                                         ineffassign  ineffectual assignment to `err`
src/configcenter/src/common/util/lib_test.go:160:2                                                     ineffassign  ineffectual assignment to `language`
src/configcenter/src/source_controller/coreservice/core/association/instance_test.go:92:2              ineffassign  ineffectual assignment to `asstInstResult`
```

What made this difference? And I found the second output more accurate.

**Comment by Helcaraxan** [comment]
It would be handy to have some of the code examples that trigger this specific situation... however I believe I have a possible explanation for the behaviour you are seeing and a code example that triggers it.

The code, part of a Go module dedicated to this example:
```go
// Content of go.mod
module test
```

```go
// Content of main.go
package main

import (
	"fmt"

	"test/lib"
)

func main() {
	val := 1
	fmt.Println(val)
	val = lib.DeprecatedInt()
}
```

```go
// Content of lib/lib.go
package lib

// Deprecated: DeprecateInt should not be used.
func DeprecatedInt() int {
	return 2
}
```

The following potential linting errors exist in `main.go` (non-exhaustive list):
1. `main.go:12:2: ineffectual assignment to `val` (ineffassign)`
2. `main.go:12:8: SA1019: lib.DeprecatedInt is deprecated: DeprecateInt should not be used.  (staticcheck)`

If you run `golangci-lint --no-config --enable-all` error 1. will show up. However if you instead run `golangci-lint --no-config --disable-all --enable=staticcheck` error 2. will show up.

This is because `golangci-lint` generally only reports one error per line (you can see the filter in question [here](https://github.com/golangci/golangci-lint/blob/d2b1eea2c6171a1a1141a448a745335ce2e928a1/pkg/result/processors/uniq_by_line.go#L28-L52) including the [hard-coded limit](https://github.com/golangci/golangci-lint/blob/d2b1eea2c6171a1a1141a448a745335ce2e928a1/pkg/result/processors/uniq_by_line.go#L43) at 1 error-per line).

-----

Now to your question / issue:

What I suppose is happening to you (although I can't be certain without seeing the code) is that when running `golangci-lint run --disable-all --enable=ineffassign` it correctly reports all hits found by the `ineffassign` linter which naturally pass the `grep ineffassign` to which you pipe the output.

On the other hand when you run with the `--enable-all` flag, other linters pick up errors as well on some of the same lines as `ineffassign`. These alternative errors happen to be given preference by `golangci-lint`'s filtering and as a result the `ineffassign` errors are silenced. When piping the resulting output through `grep ineffassign` you'll filter out the alternative errors reported on the same lines but by other linters.

You should be able to easily confirm or refute this hypothesis by taking one of the `ineffassign` errors that disappears when running with `--enable-all` and grepping for the path + line on which the error is reported, instead of grepping for the linter name. The same line should show up but with an error from another linter.
