### ISSUE TITLE
Override linter selection with the command line

### ISSUE THREAD

**Issue by abustany** [golangci/golangci-lint#715]
Version: `1.18.0 built from 31afdf8`

It doesn't seem to be possible at the moment to disable specific linters for a given run: if a linter is enabled in the configuration file, disabling it using `-D` on the command line will result in an error. Would it make sense to consider that command line options have a higher precedence than the configuration file, instead of seeing this as a conflict?

The background for this issue is that we want to have different defaults for developers and for our CI pipeline, while sharing the bulk of the configuration. Having two config files would lead to lots of duplicated information...

**Comment by Roshan-Mehta1** [comment]
Yes, This will be very handy option. Currently, We need to enable as well as disable linter explicitly. Some type of precedence would be great. 
1. Command line option should be higher precedence than configuration file.
2. And Instead of throwing error, We can make Disable as higher precedence than Enable.
