### ISSUE TITLE
Unable to install golangci-lint v1.20.1 in Linux

### ISSUE THREAD

**Issue by uvletter** [golangci/golangci-lint#873]
```bash
$ go version
# go version go1.12.13 linux/amd64

$ uname -a
# Linux n224-027-011 4.14.81.bm.7-amd64 #1 SMP Debian 4.14.81.bm.9-amd64 (2019-04-25) x86_64 GNU/Linux

$ GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.20.1
# go: finding github.com/golangci/tools v0.0.0-20180902102414-2cefd77fef9b
# go: github.com/golangci/tools@v0.0.0-20180902102414-2cefd77fef9b: unknown revision 2cefd77fef9b
# go: error loading module requirements
```

**Comment by tpounds** [comment]
@uvletter This is a known issue[1] when installing via `go get` due to non-transtivie support for the `replace` directive within the `go.mod` file. It is recommended to install directly using a binary release, however, you can work around the issue by copying the `replace` directive into your own project's `go.mod` file. Keep in mind doing this is likely to be error prone since you will have to get it updated as you upgrade releases.

[1] https://github.com/golangci/golangci-lint#go-get
